config:
  target: "http://localhost:5000/api"
  phases:
    - duration: 10
      arrivalRate: 200
      name: HardTest
  payload:
    - path: "all-csv/users.csv"
      fields:
        - "email"
        - "password"
    - path: "all-csv/fakeUsers.csv"
      fields:
        - "fakeEmail"
        - "fakePassword"
    - path: "all-csv/roomTitle.csv"
      fields:
        - "title"
    - path: "all-csv/roomData.csv"
      fields:
        - "roomName"
        - "typeId"
        - "page"
        - "limit"
    - path: "all-csv/roomId.csv"
      fields:
        - "roomId"
    - path: "all-csv/chatId.csv"
      fields:
        - "chatId"

scenarios:
  - name: "get all rooms"
    flow:
      - get:
          url: "/room"
          expect:
            - statusCode: 200
  - name: "get rooms by name"
    flow:
      - get:
          url: "/room"
          qs:
            name: "{{ title }}"
          expect:
            - statusCode: 200
  - name: "get rooms from different pages"
    flow:
      - get:
          url: "/room"
          qs:
            name: "{{ roomName }}"
            typeId: "{{ typeId }}"
            page: "{{ page }}"
            limit: "{{ limit }}"
          expect:
            - statusCode: 200

  - name: "get one room"
    flow:
      - get:
          url: "/room/{{ roomId }}"
          expect:
            - statusCode: 200

  - name: "check auth"
    flow:
      - get:
          url: "/user/auth"
          expect:
            - statusCode: 401
  - name: "try login with fake data"
    flow:
      - post:
          url: "/user/login"
          json:
            email: "{{ fakeEmail }}"
            password: "{{ fakePassword }}"
          expect:
            - statusCode: 500
          capture:
            - json: "$.token"
              as: "fakeToken"
  - name: "get all message in one chat"
    flow:
      - get:
          url: "/message"
          qs:
            chatId: "{{ chatId }}"
          expect:
            - statusCode: 200
  - name: "user road"
    flow:
      - post:
          url: "/user/login"
          json:
            email: "{{ email }}"
            password: "{{ password }}"
          capture:
            - json: "$.token"
              as: "token"
          expect:
            statusCode:
              - 500
              - 200
      - get:
          url: "/user/auth"
          headers:
            Authorization: "Bearer {{ token }}"
      - get:
          url: "/room"
          qs:
            name: "{{ roomName }}"
            typeId: "{{ typeId }}"
            page: "{{ page }}"
            limit: "{{ limit }}"
          headers:
            Authorization: "Bearer {{ token }}"
          expect:
            - statusCode: 200
      - get:
          url: "/room/{{ roomId }}"
          headers:
            Authorization: "Bearer {{ token }}"
          capture:
            - json: "$.contentId"
              as: "contentId"
            - json: "$.chatId"
              as: "chatId"
          expect:
            - statusCode: 200
      - get:
          url: "/content"
          qs:
            id: "{{ contentId }}"
          headers:
            Authorization: "Bearer {{ token }}"
          expect:
            - statusCode: 200
      - get:
          url: "/chat"
          qs:
            id: "{{ chatId }}"
          headers:
            Authorization: "Bearer {{ token }}"
          expect:
            - statusCode: 200
      - get:
          url: "/message"
          qs:
            chatId: "{{ chatId }}"
          headers:
            Authorization: "Bearer {{ token }}"
          expect:
            - statusCode: 200